UXD storybook markdown files and images
RedHatInsights/insights-frontend-storybook pull request #67
Opened 2019-05-31 13:33 UTC by beccaglass

-resolved comments from last PR
-fixed markdown files
-deleted unnecessary photos from img folder

2019-05-31 13:41 UTC, ryelo requested changes

2019-05-31 13:41 UTC, ryelo commented on src/docs/uxd/actionsOnSystems/DOC.md
> +# Actions on systems
New line after this line

2019-05-31 13:41 UTC, ryelo commented on src/docs/uxd/actionsOnSystems/DOC.md
> +## Service view of a system
New line after this line

2019-05-31 13:41 UTC, ryelo commented on src/docs/uxd/actionsOnSystems/DOC.md
> +## Inventory view of a system
New line after this line

2019-05-31 17:25 UTC, katierik approved these changes
Nice work Becca!

2019-06-03 11:47 UTC, ryelo approved these changes

2019-06-03 11:47 UTC, ryelo commented
🎉

2019-06-03 11:47 UTC, merged